import { Link } from 'react-router-dom'
import PageShell from '../../components/public/PageShell'
import QuickCalculator from '../../components/public/QuickCalculator'
import Faq from '../../components/public/Faq'
import Footer from '../../components/Footer'

const FAQ_ITEMS = [
  {
    q: 'What is the difference between Ib, In and Iz?',
    a: 'Ib is the design current — what the circuit actually needs to carry. In is the rating of the protective device (MCB, MCCB or fuse) selected to protect it. Iz is the actual current-carrying capacity of the installed cable, after correction factors. BS7671 Regulation 433.1.1 requires Ib ≤ In ≤ Iz.',
  },
  {
    q: 'Do I always need to check voltage drop, or only current rating?',
    a: 'Both, always. They are independent checks. A cable can pass the current rating check comfortably and still fail on voltage drop, particularly on longer runs — see the voltage drop guide.',
  },
  {
    q: 'What is the adiabatic check and when do I need it?',
    a: 'The adiabatic check (Regulation 543.1.3) verifies the cable — or its earth conductor — can withstand the heat generated by a fault current for the time it takes the protective device to disconnect, without being damaged: S = (I × √t) / k. It needs a prospective fault current figure, which this quick guide doesn\'t collect — use the full calculator for short-circuit and adiabatic checks.',
  },
  {
    q: 'Can I use this method for aluminium conductors?',
    a: 'Yes, with a different k factor (76, versus 143 for copper XLPE or 115 for copper PVC, per Table 54.4) and different Appendix 4 tables (4D3A/4D4A for PVC, 4E3A/4E4A for XLPE). Aluminium\'s minimum practical size is usually 16mm².',
  },
]

export default function Bs7671Guide() {
  return (
    <PageShell
      crumbs={[{ label: 'Home', to: '/' }, { label: 'Guides', to: '/guides/bs7671-cable-sizing-explained' }, { label: 'Cable sizing explained' }]}
      eyebrow="Guide"
      title="BS7671 Cable Sizing, Explained"
      intro="The full method BS7671:2018+A2 uses to size a cable — design current, correction factors, current rating, voltage drop and the adiabatic check — with a worked calculator at each step."
    >
      <article className="article">
        <h2>The five checks BS7671 requires</h2>
        <p>
          Cable sizing to BS7671 isn't a single lookup — it's a sequence of checks that all
          have to pass simultaneously. Get any one of them wrong and the "correct" size from
          the others is still non-compliant. This guide walks through each step in order,
          the way BS7671:2018 Amendment 2 Appendix 4 and Section 525 define it.
        </p>

        <h3>1. Determine the design current, Ib</h3>
        <p>
          Ib is the current the circuit actually needs to carry under normal load — read
          directly from equipment ratings, calculated from kW and voltage for resistive
          loads (<code>Ib = P / V</code> for single-phase), or derived from motor
          nameplate data with efficiency and power factor for motor circuits.
        </p>

        <h3>2. Select the protective device, In</h3>
        <p>
          Choose an MCB, MCCB, fuse or RCBO with a standard rating at or above Ib. BS7671
          Regulation 433.1.1 requires <code>Ib ≤ In</code>.
        </p>

        <h3>3. Read the tabulated rating, It</h3>
        <p>
          Using BS7671 Appendix 4, look up the tabulated current-carrying capacity for the
          cable's insulation (PVC 70°C or XLPE 90°C), configuration (multicore or
          single-core) and installation reference method (A1 through G — see the{' '}
          <Link to="/tables/bs7671-cable-current-rating-tables">full tables</Link>).
          This figure assumes ideal conditions: 30°C ambient, installed alone, no thermal
          insulation contact.
        </p>

        <h3>4. Apply the correction factors to get Iz</h3>
        <p>
          Real installations rarely match those ideal conditions, so four factors correct
          It down to the actual current-carrying capacity, Iz:
        </p>
        <ul>
          <li><strong>Ca</strong> — ambient temperature, if not 30°C</li>
          <li><strong>Cg</strong> — grouping, if the cable shares a route with other loaded circuits</li>
          <li><strong>Ci</strong> — thermal insulation, if the cable is in contact with insulation</li>
          <li><strong>Cc</strong> — protective device type (only BS3036 semi-enclosed fuses need a factor below 1.00)</li>
        </ul>
        <p>
          <code>Iz = It × Ca × Cg × Ci × Cc</code>, and Regulation 433.1.1 requires{' '}
          <code>In ≤ Iz</code> — combined with step 2, the full chain is{' '}
          <code>Ib ≤ In ≤ Iz</code>.
        </p>

        <h3>5. Check voltage drop</h3>
        <p>
          Independently of current rating, BS7671 Section 525 limits voltage drop to 3% of
          nominal voltage for lighting circuits and 5% for others, calculated from the
          cable's mV/A/m figure, its length and the design current. See the{' '}
          <Link to="/calculator/voltage-drop">voltage drop calculator</Link> for the full
          method — this is frequently what actually decides the final cable size on longer
          runs, not the current rating.
        </p>

        <h3>6. Check the adiabatic (short-circuit) withstand</h3>
        <p>
          If a prospective fault current is available, Regulation 543.1.3 requires the
          minimum conductor size to satisfy <code>S = (I × √t) / k</code>, where I is the
          fault current, t is the protective device's disconnection time, and k is a
          material and insulation constant (143 for copper XLPE, 115 for copper PVC, 76 for
          aluminium, per Table 54.4). This step needs fault-level data that a quick sizing
          tool doesn't collect — it's covered in the full calculator.
        </p>
      </article>

      <div style={{ marginTop: 8 }}>
        <QuickCalculator
          note="Try the sequence above on your own circuit — enter Ib, In, length and installation method."
        />
      </div>

      <div style={{ marginTop: 40 }}>
        <Faq items={FAQ_ITEMS} />
      </div>

      <div className="related-pages">
        <Link to="/calculator/swa-armoured-cable-size">
          <div className="label">Calculator</div>
          <div className="title">SWA / armoured cable size →</div>
        </Link>
        <Link to="/tables/bs7671-cable-current-rating-tables">
          <div className="label">Reference</div>
          <div className="title">Full BS7671 current rating tables →</div>
        </Link>
        <Link to="/calculator">
          <div className="label">Tool</div>
          <div className="title">Full calculator — fault current, PDF export →</div>
        </Link>
      </div>

      <Footer />
    </PageShell>
  )
}
